## Dot envs
#$ZDOTDIR/.zshenv
#$ZDOTDIR/.zshrc

# Settings
autoload -U colors && colors
PS1="%{$fg[green]%}❯%{$reset_color%} "
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
set -o vi
eval "$(/opt/homebrew/bin/brew shellenv)"
setopt auto_cd

# History
HISTFILE=~/.histfile
HISTSIZE=3000
SAVEHIST=3000
HISTDUP=erase
setopt HIST_IGNORE_SPACE
setopt appendhistory
setopt hist_find_no_dups
setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_save_no_dups
setopt incappendhistory
setopt sharehistory
setopt interactivecomments

alias ls=exa
alias ll='ls -l'
alias tree='exa --tree -l'
alias pwdd='TZ=America/New_York date; pwd'
